version: '3.6'
services:
  jenkins:
    container_name: jenkins
    image: 'jenkins/docker'
    build:
      context: pipeline
    ports:
      - '8080:8080'
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: 'remote-host'
    build:
      context: centos7
    volumes:
      - $PWD/aws-s3.sh:/tmp/script.sh
    networks:
      - net
  prod_host1:
    container_name: prod-host1
    image: 'prod-host1'
    build:
      context: prod1
    volumes:
      - $PWD/aws-s3.sh:/tmp/script.sh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  prod_host2:
    container_name: prod-host2
    image: 'prod-host2'
    build:
      context: prod2
    volumes:
      - $PWD/aws-s3.sh:/tmp/script.sh
    networks:
      - net
  db_host:
    container_name: db
    image: 'mysql:8'
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234test
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net
  git:
    container_name: 'git-server'
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.yeahbutstill.badass.world'
    ports:
      - '8090:80'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    networks:
      - net
networks:
  net:
